import Banner from "@/components/banner/Banner";
import Healthy from "@/components/healthy/Healthy";
import Navbar from "@/components/layout/Navbar";
import StaticBar from "@/components/staticBar/StaticBar";
import Workout from "@/components/workout/Workout";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gym baran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="author"
          content="Ripon Hossain Shuvo | rhshuvo44@gmail.com"
        />
      </Head>
      <Navbar>
        <Banner />
        <Healthy />
        <StaticBar />
        <Workout />
      </Navbar>
    </>
  );
}
